[package]

name = "ducky"
version = "0.0.1"
authors = [ "Michael Layzell <michael@thelayzells.com>" ]
repository = "https://github.com/mystor/ducky"
readme = "README.md"

[dependencies.string_cache]

git = "https://github.com/mystor/string-cache.git"
branch = "std-sync"

[[bin]]

name = "duckyc"
