[package]

name = "lang"
version = "0.0.1"
authors = [ "Michael Layzell <michael@thelayzells.com>" ]

[dependencies.lambdas]

git = "https://github.com/mystor/lambda-macro.git"

[[bin]]

name = "lang"
