[package]

name = "ducky"
version = "0.0.1"
authors = [ "Michael Layzell <michael@thelayzells.com>" ]
repository = "https://github.com/mystor/ducky"
readme = "README.md"

[dependencies]

regex = "0.1.10"
regex_macros = "0.1.5"
lazy_static = "0.1.*"

[[bin]]

name = "duckyc"
