[package]

name = "lang"
version = "0.0.1"
authors = [ "Michael Layzell <michael@thelayzells.com>" ]

[dependencies.string_cache]

git = "https://github.com/servo/string-cache.git"

[[bin]]

name = "lang"
